### ISSUE TITLE
Bug in setup.py

### ISSUE THREAD

**Issue by apertome** [esnet/tstat-transport#1]
When trying to install on CentOS 6, we can't due to a missing README.md. It won't install.

```
# python -V
Python 2.7.8
# pip install tstat_transport
You are using pip version 7.1.0, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting tstat-transport
  Downloading tstat_transport-0.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-yoWr_D/tstat-transport/setup.py", line 15, in <module>
        DESCRIPTION = open('README.md').read()
    IOError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yoWr_D/tstat-transport
```

**Comment by montegoode** [comment]
@apertome I will get right on this and push something soon.

**Comment by montegoode** [comment]
Fixed in this commit: https://github.com/esnet/tstat-transport/commit/e0d0fabb803a988b47fcd06dcf6a8802ae05b411

Sorry about that!
